### ISSUE TITLE
Run machete in a submodule

### ISSUE THREAD

**Issue by syl8o** [VirtusLab/git-machete#1]
When running git-machete edit in a submodule, command fails with following error :

`Traceback (most recent call last):
  File "/usr/local/bin/git-machete", line 812, in <module>
    open(definition_file, 'w').close()
IOError: [Errno 20] Not a directory: '/home/sprudent/web/src/sites/api.osmozis.com/access/v1/.git/machete'`

This is because a submodule does not have a .git folder but a file refering to the parent module's .git folder instead.

Too bad because the tool looks very helpfull!

**Comment by PawelLipski** [comment]
Thanks for reporting the error, will fix that when time allows :)

**Comment by syl8o** [comment]
I managed to find a fix, i will try to send you a pull request if you want.

**Comment by PawelLipski** [comment]
Okey, I'd be grateful for a PR. I'd probably go for using `--git-dir` flag for `rev-parse` instead of `--show-toplevel`... curious what's your solution though.

**Comment by syl8o** [comment]
I didn't see your branch, your solution is cleaner. I was checking if .git was file or folder and in the case it was a file, parsing git-dir in the file. But using --git-dir is safer I think.
I never had to use git rev-parse but it looks powerfull.

**Comment by PawelLipski** [comment]
@sprudent made a new release (v1.0.2) that fixes the issue

**Comment by PawelLipski** [comment]
@sprudent out of curiosity - did you find any other issues/space for improvement when using `git machete` in submodules?

**Comment by syl8o** [comment]
@PawelLipski It is working like a charm for the moment, I will tell you if i find something else.
