### ISSUE TITLE
UI - blurred text

### ISSUE THREAD

**Issue by KrystianUjma** [VirtusLab/git-machete#10]
I use a terminal with white background. When i use `git machete discover` I see a "untracked" text with yellow font which is blurred on white background. Can you change it to another color please, which also gonna be fine on dark background too?

**Comment by PawelLipski** [comment]
@Veezq thanks for reporting, please take a look at the branch `bugfix/white-term-colors` (tag `v2.7.1-RC`)

**Comment by PawelLipski** [comment]
Done, resolved as of v2.7.1
