### ISSUE TITLE
Consider allowing to automatically remove missing branches from the machete file

### ISSUE THREAD

**Issue by radeusgd** [VirtusLab/git-machete#100]
# Overview

When a branch is removed manually (for example with `git branch -d <name>`), but is still present in the machete tree, I get an error when running status for example.

While I guess it is recommended to use `git machete slide-out` for this usecase, it would be good if a normal git command did not break the machete.

It is of course a very low priority thing, because it can easily be solved by editing the machete file, as indicated in the error, but it could be much more useful if the tool asked to remove the branch automatically.

## Expected behavior/subcommand output

```
# git branch -d <name>
# git machete status -L
<name> is not a local branch, perhaps it was deleted.
Do you want machete to remove it from the configuration file?
(You can also edit the definition file manually with git machete edit)
[y/n] y
<name> has been deleted from the tree.
<shows the requested status>
```

## Actual behavior/subcommand output

```
# git branch -d <name>
# git machete status -L
.git/machete, line 2: <name> is not a local branch. Edit the definition file manually with git machete edit
```

## `git` and `git machete` versions

```
# git --version
git version 2.17.1

# git machete --version
git-machete version 2.15.3

```

**Comment by PawelLipski** [comment]
Thank you @radeusgd! I'll include that in 2.15.4 soon (as in, not blocking the release of this one on other in-development features).

Just thinking aloud... do you think the choice b/w:
1. sliding out the branch
1. checking out the branch from the current HEAD
1. checking out the branch from its parent

would make sense or is it an overkill? As in, do you observe yourself ever creating the branch `<name>` in `<name> is not a local branch` situations?

**Comment by radeusgd** [comment]
Hm, it depends on how the machete file is managed.

If it is mostly created by `git machete discover` modulo some manual modifications, I don't think a check out would ever be needed, as the branch should appear in the file only if it existed at some point. And if it existed earlier and does not exist now, it must have been removed, most likely on purpose. So personally, I think I'd only ever use (1).

However I can think of a scenario where the branch got somehow removed by accident, in such case (3) seems like it also could be helpful.

Additionally, if someone synchronised their machete file between computers, I guess (3) may also be helpful when a branch was added on the other machine.
