### ISSUE TITLE
`git machete discover` crashes if no roots can be found

### ISSUE THREAD

**Issue by radeusgd** [VirtusLab/git-machete#103]
# Overview

When the repository does not contain any known roots (i.e. `master` or `develop`) nor roots are specified explicitly with `--roots=...`, running `git machete discover` crashes with a `NameError`.

## Expected behavior/subcommand output

Ideally, git-machete should automatically discover the root branch. Technically, it is possible by traversing the commit tree, the branch that is associated with the initial commit (i.e. one without parents) is a root branch. But this traversal may take some time, so I'm not sure if it should be used, you may want to test it if it impacts performance (although root discovery is if I understand correctly only done in `discover` and that one isn't used *that* often, so maybe it's possible to do that).

Alternatively, in case that no root can be detected, I would expect to get a meaningful error message, something like "Cannot automatically determine the root branch, you can use the `--roots` option to manually specify which branches should be treated as roots".

## Actual behavior/subcommand output

The program crashes with a `NameError`:

```
Traceback (most recent call last):
  File "/snap/git-machete/51/bin/git-machete", line 4, in <module>
    cmd.main()
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 3053, in main
    launch(sys.argv[1:])
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 3292, in launch
    discover_tree()
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 1494, in discover_tree
    non_root_fixed_branches = excluding(all_local_branches, roots)
NameError: name 'roots' is not defined

```

## `git` and `git machete` versions

```
> git --version
git version 2.17.1


git machete --version
git-machete version 2.15.5
```

## Additional diagnostics info

I attach an example repository that reproduces this issue.

```
> git machete --debug discover
>>> git rev-parse --git-dir
<stdout>:
.git

>>> git for-each-ref --format=%\(refname\)$'\t'%\(objectname\)$'\t'%\(committerdate:raw\) refs/remotes
>>> git for-each-ref --format=%\(refname\)$'\t'%\(objectname\)$'\t'%\(committerdate:raw\)$'\t'%\(upstream\) refs/heads
<stdout>:
refs/heads/b1	1906a3bd3fe95fe003ab37c96d784ab5e4ca21e0	1600442872 +0200	
refs/heads/main	fa6945279b24c7914b8541029f7d1e8d82835a76	1600442845 +0200	

Traceback (most recent call last):
  File "/snap/git-machete/51/bin/git-machete", line 4, in <module>
    cmd.main()
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 3053, in main
    launch(sys.argv[1:])
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 3292, in launch
    discover_tree()
  File "/snap/git-machete/51/lib/python3.6/site-packages/git_machete/cmd.py", line 1494, in discover_tree
    non_root_fixed_branches = excluding(all_local_branches, roots)
NameError: name 'roots' is not defined
```

Of course any repository without `master` or `develop` branches will work.
[gmtdiscover.zip](https://github.com/VirtusLab/git-machete/files/5246503/gmtdiscover.zip)

**Comment by PawelLipski** [comment]
Thanks for the issue! This is likely only introduced by v2.15.5 recently.
