### ISSUE TITLE
Add a config/flag to toggle between reflog-based and commit-message-based modes of fork-point

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#11]
As suggested by @ArturGajowy on #6:

> The only other improvement [of fork point algorithm] (?) that comes to my mind is using the commit messages to find the fork point (that's how a human being would do that), possibly as a fallback / togglable strategy.

This could be served by a git config `machete.fork-point.match-by`, and possible overridden on per-operation basis by `--match-by=commitmsg|reflog` flag for commands like `update`, `reapply` etc.

**Comment by PawelLipski** [comment]
@ArturGajowy FYI, I'm currently working on a more general (and more powerful, I hope) solution that would allow for arbitrary overriding of fork point for any given branch: https://github.com/VirtusLab/git-machete/compare/feature/discover-roots..yellow-edges/fork-point-override

**Comment by ArturGajowy** [comment]
Great! Thx for the heads up! Just a thought: could we have an option to use a commit message prefix for defining the forkpoint override?

**Comment by PawelLipski** [comment]
Ok, will also add an option `--override-to-parent-of-msg` and a related config entry :)

**Comment by PawelLipski** [comment]
Moved to #28
