### ISSUE TITLE
Turn on strict optional (mypy)

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete#118]
This IIUC will enable None-correctness checks similar to Kotlin or [NullnessChecker](https://checkerframework.org/manual/#nullness-checker) in Java

**Comment by PawelLipski** [comment]
For anybody who takes this task: pls first assess the scope of changes this will cause in the repo, maybe the extra soundness is not worth the extra complication/loss of readability

**Comment by PawelLipski** [comment]
Wow it's done, I forgot to close it ‼️
