### ISSUE TITLE
Support Github Enterprise endpoints

### ISSUE THREAD

**Issue by asford** [VirtusLab/git-machete#137]
The current GitHub integration only detects and targets `github.com` hosted repositories,
and is not compatible with github enterprise endpoints.

There isn't a "single standard" on how to specify Enterprise domains in github related tools.
It *may* be easiest to just detect any domains configured in `gh`, as #136 allows `machete` to delegate to `gh` for access token management already.
`gh auth status` could then be used to extract the currently configured enterprise domains.

https://cli.github.com/manual/ -> "GitHub Enterprise Server"

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete/pull/136#discussion_r654618927_

**Comment by PawelLipski** [comment]
Will be useful for us now, given that we started work in a project that uses Enterprise GH :)

**Comment by PawelLipski** [comment]
Things to consider:
- [x] `git_machete.github.GITHUB_REMOTE_PATTERNS` has `github.com` hardcoded
- [x] GitHub tokens only work on a per-domain basis: a token generated for github.com won't work for git.example.com and vice-versa. The format of .github-token needs to be extended in a backward-compatible manner to sth like:
```
ghp_12345678
ghp_87654321 git.example.com
```
i.e. one token per line, followed by domain (if missing, defaults to github.com).

- [x] extraction of token from `gh` and `hub` configs needs to be refined
- [x] `GITHUB_TOKEN` probably should stay as is (the alternative could be to use sth like `GITHUB_TOKEN_GIT_EXAMPLE_COM` but that's probably an overkill)
- [x] `Visit https://github.com/settings/tokens to generate a new one` error message has github.com hardcoded
- [ ] (TBD what else)

**Comment by PawelLipski** [comment]
@asford see the fresh [v3.14.0](https://github.com/VirtusLab/git-machete/releases/tag/v3.14.0) release 📦

**Comment by skmanohar** [comment]
I updated my config to say: 

```
[machete "github"]
        domain = my.enterprise.domain.com
        organization = skmanohar
        repository = stacked-pr-test
        remote = origin
```

`git machete github create-pr --draft` seems to be trying to connect to `https://api.my.enterprise.domain.com`, which fails with `<urlopen error [Errno 8] nodename nor servname provided, or not known>.`

I think it should be hitting `https://domain/api/v3/` insteadl. Not sure if this is a strange configuration at the enterprise server I am looking at. If not, this might be worth addressing.

**Comment by PawelLipski** [comment]
@skmanohar whoops right, apparently `api.<domain>` is just a specific redirect (?) into `<domain>/api/v3` for my current project's Enterprise GitHub. Lemme fix this asap :/

**Comment by PawelLipski** [comment]
Fix under way on PR #780...

**Comment by PawelLipski** [comment]
@skmanohar see v3.14.1, already released to all channels

Out of curiosity, how did you learn of git-machete?

**Comment by skmanohar** [comment]
>see v3.14.1, already released to all channels

I just tested, and it is working good for me.

>Out of curiosity, how did you learn of git-machete?

I was looking for a way to manage large changes at my org - enormous PRs were becoming a nightmare. Found [this](https://benjamincongdon.me/blog/2022/07/17/In-Praise-of-Stacked-PRs/) blogpost that recommended git-machete for stacked PRs.
