### ISSUE TITLE
Unify code for pulling/building/pushing Docker images for CI

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#138]
There's currently a bunch of different `ci-run.sh` scripts in subfolders under `ci/`... most of them are doing the very same thing: pull the Docker image corresponding to the current state of the subfolder from DockerHub, or build&push the image if not found there. I think this can be unified into some utility script to be shared across these subfolders.

**Comment by rifel123** [comment]
closed with #182
