### ISSUE TITLE
Optimize tests in CI so that `tox` isn't installed separately for each Python version

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#146]
An obvious solution to speed up installation would be to include `tox` within Docker image used for running the tests... but this in turn will increase the time needed for downloading the images themselves.

Let's check if this brings any speedup and think about the alternatives if it doesn't.

**Comment by BartoszSiwinski** [comment]
I can be also considered to run tests on different python-git versions pairs in parallel.

**Comment by PawelLipski** [comment]
You can contact @micpiotrowski about the caveats of this approach, I remember he tried that in https://github.com/VirtusLab/git-machete-intellij-plugin and encountered some serious blockers (which may or may not apply for this project's CI setup as well)
