### ISSUE TITLE
Move instructions for shell completion from Wiki into docs

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#147]
Just to keep all things in a single place &mdash; when anything changes wrt. how the completion is done, we should reflect it in the docs in unison.

**Comment by PawelLipski** [comment]
Esp. important wrt. #119

**Comment by mohitsaxenaknoldus** [comment]
@PawelLipski  Raised a PR for it: https://github.com/VirtusLab/git-machete/pull/209

**Comment by PawelLipski** [comment]
Done on #209, dunno why Github didn't close the issue
