### ISSUE TITLE
Line numbers displayed in errors refer to non-empty lines, not all lines

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#153]
.git/machete file:

```
master
  develop


  develop
```

The empty lines lead to an error in `git machete status`:

`.git/machete, line 3: branch develop re-appears in the tree definition. Edit the definition file manually with git machete edit`

while it should say:

`.git/machete, line 5: branch develop re-appears in the tree definition. Edit the definition file manually with git machete edit`

This is due to how `read_definition_file` is implemented, should be pretty easy to fix.

**Comment by rifel123** [comment]
fix merged into develop in #179
