### ISSUE TITLE
Extract version from __init__.py to a separate VERSION file

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#155]
As done in e.g. https://github.com/crdoconnor/strictyaml, see their [setup.py](https://github.com/crdoconnor/strictyaml/blob/master/setup.py#L19).

This will simplify extracting the version in various CI scripts, no need to some brittle `cut`s (search for `git_machete/__init__.py` across the project).

**Comment by rifel123** [comment]
Because `__version__ ` is used inside python files, to avoid problematic search of VERSION file when tool is installed via pip or egg,  it's better now to stick with current solution and keep `__version__` property in `__init__.py`
