### ISSUE TITLE
Smooth out method naming

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#160]
There's currently very little consistency in method naming: some use `get_` or `derive_` prefix while some don't, depending on nothing in particular. Let's tidy that up in either direction

**Comment by mohitsaxenaknoldus** [comment]
I can do it if you tell me the files where these inconsistent functions are.

**Comment by PawelLipski** [comment]
Nice, sure :) there is an ongoing revamp of file/package structure, performed by @rifel123 on #159 ... I think the best moment to apply that **on the files in `git_machete` package** will be once Piotr is done with this PR (which should be pretty soon). You can actually take a look there and/or even contribute to the review if you like :)

**Comment by rifel123** [comment]
Hi @mohitsaxenaknoldus, you can start contributing on this issue, coz PR #168 ins now merged :)

**Comment by garg-tanishka** [comment]
Hi @PawelLipski you can assign this to me, I can perform this task.

**Comment by rifel123** [comment]
Hi @garg-tanishka, you are assigned now :)

**Comment by PawelLipski** [comment]
Done by #181
