### ISSUE TITLE
Refactor 1-2 letter variable names to be more descriptive

### ISSUE THREAD

**Issue by BartoszSiwinski** [VirtusLab/git-machete#162]
There are few places in the code where the code is using very short, a bit enigmatic names for variables. Sometime they're also used inconsistently.

Example when iterating through roots iteration marker is called 'r' and when iterating through remotes it's also called 'r'. There are also some variables like 'u' and 'rb' that are hard to decode when reading the methods.

It would improve maintainability if the code would be more descriptive.

**Comment by mohitsaxenaknoldus** [comment]
Raised a PR: https://github.com/VirtusLab/git-machete/pull/212

**Comment by mohitsaxenaknoldus** [comment]
@PawelLipski This can be closed?

**Comment by PawelLipski** [comment]
Whoops right! dunno why it didn't close automatically 😯
