### ISSUE TITLE
Organize constants of the same context in some kind of structure

### ISSUE THREAD

**Issue by BartoszSiwinski** [VirtusLab/git-machete#163]
There are places in the code where multiple constants related to each other are defined. It would be good to refactor the repository to put them in structures. 

Example: there are separate definitions of colors RED, YELLOW, etc. They could be put into a dictionary that would also explain the context of the colors. At the moment it's not clear if it's RGB definition of a color or string 'red' or something else. Organizing it into the structure explaining the context could improve code quality.

**Comment by PawelLipski** [comment]
Looks related to #117
