### ISSUE TITLE
Test remaining commands and options

### ISSUE THREAD

**Issue by BartoszSiwinski** [VirtusLab/git-machete#170]
Following commands are yet to be tested:
* add
* anno
* delete-unmanaged
* diff
* edit
* file
* fork-point
* format
* hooks
* is-managed
* list
* log
* reapply
* squash (with option fork-point)
* status
* update (with option interactive)
* version.

**Comment by PawelLipski** [comment]
Note: `format` and `hooks` are not commands per se, just help topics (so they're probably covered within the existing test for `help`)

**Comment by PawelLipski** [comment]
Let's first check coverage, probably quite a lot of them are already covered (mostly thanks to some ad-hoc regression tests added after bugs)
