### ISSUE TITLE
Keep the contents of Docker-setup blogs in this repo + update with recent changes

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#174]
Similarly to how https://github.com/VirtusLab/git-machete/issues/121 has been done.

Various details in blogs:

1. https://medium.com/virtuslab/nifty-docker-tricks-for-your-ci-vol-1-c4a36d2192ea
2. https://medium.com/virtuslab/nifty-docker-tricks-for-your-ci-vol-2-c5191a67f1a4

are pretty out of date by now.

The contents are kept under https://github.com/PawelLipski/docker-ci-blog ... let's keep them in this repo under `docs/` to keep them more up to date more easily.

**Comment by BartoszSiwinski** [comment]
docs/ folder will be used for building actual documentation in #106, so there will be a new folder called blogs that will store relevant information. What's more there will be 2 merges needed to pass initial_checks run, since it's checking if links in CONTRIBUTION.md file are correct.
