### ISSUE TITLE
Create-pr: Check if reviewers belong to current organisation on Github

### ISSUE THREAD

**Issue by rifel123** [VirtusLab/git-machete#177]
Currently there is no check performed before adding reviewers to pull request, which causes HTTP 422 error `UnprocessableEntity`. There has to be check before if reviewer belongs to organisation. Informations about organization can be found under [orgs endpoint](https://docs.github.com/en/rest/reference/orgs) or directly  under [members endpoint](https://docs.github.com/en/rest/reference/orgs#list-organization-members)

**Comment by PawelLipski** [comment]
See #342, probably obsolete

**Comment by rifel123** [comment]
Could be obsolete. Here is exact message body when trying to add reviewers which are not collabolators:
`{'message': 'Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the rifel123/sandbox repository.', 'documentation_url': 'https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request'}`

In this case information about failure can be taken directly from `message` field, which differs from other 422 message errors, where info is taken from `errors` fields. First we need to unify it.

**Comment by rifel123** [comment]
closed with #347
