### ISSUE TITLE
Add test for `github` command

### ISSUE THREAD

**Issue by rifel123** [VirtusLab/git-machete#178]
Since `github` command has been added in version 3.4.0, there is need to  add tests for following commands:
- `github create-pr`
- `github anno-prs`
- `github retarget-pr`

Can be done together or separately with issue #170 

EDIT: plus also `github checkout-pr` once it's implemented within #175 (preferably tests added alongside the new subcommand)

**Comment by PawelLipski** [comment]
This would ideally include opening a local server that would mimic the parts of github API that we're interested in... although this might be hard without a full Github on-premises instance 😅 maybe sth like https://github.com/altany/docker-github-api ? Or just a mock http server that would replay pre-recorded responses?

**Comment by PawelLipski** [comment]
If not, then opening an test repo on github (within @git-machete-bot user) is also an option, albeit potentially a more unstable/less reproducible one

**Comment by rifel123** [comment]
Closed with PR #214
