### ISSUE TITLE
Reduce the amount of spam displayed by the `git_machete.tests.functional.test_machete.MacheteTester.setUp` and `setup_discover_standard_tree`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#183]
There's a looot of spam coming from the sandbox setup code, as you can see in the CI logs:

![image](https://user-images.githubusercontent.com/3383210/130483690-620620ec-5db1-4397-81a5-19b1b7946803.png)

Pls find out a way to reduce the verbosity... probably passing `--quiet`/`-q` flag to the `git` commands invoked by the test setup code could be the way?

**Comment by PawelLipski** [comment]
Or maybe better, capture the output via similar mechanism as in `git_machete.tests.functional.test_machete.MacheteTester.launch_command`, and only print it out if a specific environment variable is set to `true` (?)

**Comment by PawelLipski** [comment]
(Assigned to @garg-tanishka, can't assign people from outside the org directly via GitHub :/)

**Comment by garg-tanishka** [comment]
> (Assigned to @garg-tanishka, can't assign people from outside the org directly via GitHub :/)

It's okay. Thankyou!

**Comment by PawelLipski** [comment]
Done on #204
