### ISSUE TITLE
Is it possible for PEP8 check to fail against one Python version if it passed against another?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#184]
We're currently running pep8 check in the CI for each supported Python version ([3.6, 3.9]).
But is it really needed? Maybe just running against one version is enough?

~Same point applies to `black` check, which is to be implemented within the scope of #140 (and will probably replace pep8 check).~ EDIT, we resigned from `black`, too opinionated

**Comment by PawelLipski** [comment]
Let's actually consider figuring this out to be a prerequisite for #140

**Comment by rifel123** [comment]
Well, as far as i know, it's not possible to fail just for one version and pass against another, because PEP8 are general rules for python not distinguished for certain versions. What is more, whole internet,  does not mention about such a case, so probably  fail for just one version of python was never observed. I suggest to run Flake8 checks only  for one python version.

**Comment by PawelLipski** [comment]
Okay... one thing, if you could check what are the actual  changes introduced b/w 3.6 ... 3.9, as TBH I'm not aware of anything at the moment other than `@dataclass` being added in 3.7. Esp. whether there are any changes to the language syntax itself... coz they're more likely to involve pep8-related changes (as compared to e.g. adding new APIs).

**Comment by rifel123** [comment]
New features added:
Python 3.7:
- [context vars](https://docs.python.org/3/library/contextvars.html#module-contextvars)
- [dataclasses](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass)

Python 3.8:
- [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata)
- dynamic variable assignment in conditions - not a module but introduces new operator `:=`

Python 3.9:
- [zone info](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo)

Of course there was a lot more of changes, but those listed above introduce new syntax, rest of changes are changes in built-in functions behaviour and performance improvements.

In Git Machete we do not use any of introduced recently features, but even if we do, it still would not be a concern for PEP8 point of view, which enforces for egz. whites spaces around operators, it's not quite connected to syntax.

**Comment by PawelLipski** [comment]
Okay... so indeed, if you could remove redundant `pep8` tox envs in the CI and let's close this issue

**Comment by rifel123** [comment]
closed with #262
