### ISSUE TITLE
Does `yq` option make sense in `git machete github create-pr`?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#186]
I'm just dogfooding the new feature on another project... and a random observation, is presenting the `yq` choice (in either _untracked_ or _ahead of remote_ case) justified? It's rather an unlikely scenario that someone uses `git machete github create-pr` just to push branch and then resigns from creating the PR 🤔

Also... how does the `n` choice make sense in the _untracked_ case? won't it always end up in a failure (since the branch is NOT pushed, but an attempt to create a PR for an untracked branch still happens) ❓

**Comment by PawelLipski** [comment]
Also! For readability, I'd add a empty line b/w status and `Creating PR...` message:

![image](https://user-images.githubusercontent.com/3383210/130663645-75e414f1-b1a9-4b4b-bbd9-026836e2f5fd.png)

**Comment by PawelLipski** [comment]
Whoops... as mentioned above, `n` option isn't probably a good idea...

![image](https://user-images.githubusercontent.com/3383210/130667770-a1b3bab0-165c-4c03-8ab0-3079e1fc25f6.png)

And the `Please open an issue regarding this topic under link` message is out of place here :/

**Comment by rifel123** [comment]
closed in #192
