### ISSUE TITLE
Unnecessary attempt to create pull request when child branch is equal to parent branch

### ISSUE THREAD

**Issue by rifel123** [VirtusLab/git-machete#193]
This attempt end up with error, cause there is no difference between those two branches.
there is check for this issue:
<img width="488" alt="Screenshot 2021-08-26 at 10 56 33" src="https://user-images.githubusercontent.com/73847352/130933536-2c13f9cb-96d9-4b9f-992b-cff1e9ee2c29.png">

but it passes when current branch has no new commit. It's because `filtered_reflog` method excludes every branch creation from reflog.

Maybe there is need to make dedicated check in this case?

**Comment by rifel123** [comment]
And there should be `MacheteException` raised with proper message instead of return on screenshot above.

**Comment by PawelLipski** [comment]
Hmmm `__is_merged_to_upstream` is a pretty high-level check, used to determine whether a branch is linked with its parent with a gray edge... probably a simpler/more low-level check should be used here 🤔

**Comment by PawelLipski** [comment]
Also, TBD what happens when the child (machete-wise) branch is NOT equal, but an ancestor (commit-wise) of parent branch 🤔 probably Github also refuses to create a PR under such circumstances

**Comment by rifel123** [comment]
closed with #230
