### ISSUE TITLE
No way to run mypy checks without running tests as well

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#196]
There should be a separate env in tox.ini for mypy, just as it is for pep8 checks

**Comment by ronnie-llamado** [comment]
I'd like to take on this issue.

**Comment by PawelLipski** [comment]
Great! 🎉 

Out of curiosity, how did you get to know about this project?

**Comment by ronnie-llamado** [comment]
I found it by searching for `"good first issue"`'s in [Issues](https://github.com/issues).

I was looking for some issues to get more exposure to some python tools and it's a good excuse to dig through some repositories to learn a thing or two.  It's a bonus that I can definitely see myself using this project in the future.

**Comment by PawelLipski** [comment]
Done in #241 🥳
