### ISSUE TITLE
Commission documentation on the readthedocs

### ISSUE THREAD

**Issue by BartoszSiwinski** [VirtusLab/git-machete#210]
One of the maintainers have to sync their account with the rtd account and give permission to modify administrated repo which in turn should result in rtd being able to add hooks to the project and open a possibility to update documentation with every push. Appropriate branch should also be chosen (develop, master, develop and master?), which versions should be maintained (latest, stable, latest and stable?).

Connected to (and blocked by) #202

**Comment by BartoszSiwinski** [comment]
Also, we should add link to RTD documentation from README.

**Comment by BartoszSiwinski** [comment]
Might be useful:
https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by PawelLipski** [comment]
Done, I've been added to RtD project by Bartosz.
