### ISSUE TITLE
Include git version (not just Python version) in CircleCI job names

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#220]
Since e.g. this job https://app.circleci.com/pipelines/github/VirtusLab/git-machete/661/workflows/668b9317-7743-476a-a04a-a50ea32df7d8/jobs/1391 is displayed as failing `tests_py36` in Github... while the failure here was related NOT to Python version, but rather to the old git version, this might be confusing. Also, maybe use more friendly format like `test python 3.6, git 1.8.10` if possible

**Comment by rifel123** [comment]
closed with #262
