### ISSUE TITLE
Docker blog #2 has a gap in the narrative after the recent script refactors

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#222]
Specifically, the part after:

```markdown
We already know that `GIT_VERSION` and `PYTHON_VERSION` are set up directly by CircleCI based on values specified in `.circleci/config.yml`.
Let's peek into [ci/tox/ci-run.sh](https://github.com/VirtusLab/git-machete/blob/develop/ci/tox/ci-run.sh) to see where `DIRECTORY_HASH` comes from:
```

`ci/docker-build-and-push.sh` is mentioned but not listed in a snippet... in the later paragraphs (`Once we've got the directory hash, we check (docker-compose pull)...`) there are references to the stuff that happens in `ci/docker-build-and-push.sh` ☹️

**Comment by BartoszSiwinski** [comment]
Currently `ci/tox/ci-run.sh` via `source ci/docker-build-and-push.sh tox` calls `ci/docker-build-and-push.sh` which in turn executes 
```
DIRECTORY_HASH=$(git rev-parse HEAD:ci/$image_name)
export DIRECTORY_HASH
```
so I've specified that to find definition of `DIRECTORY_HASH` let's look to `ci/tox/ci-run.sh` that doesn't have it but calls `ci/docker-build-and-push.sh` that does.

Where is the gap?

**Comment by PawelLipski** [comment]
I have an assumption that every code snippet that's relevant to the narrative should be explicitly listed in the blog! So that the reader doesn't need to switch to Github to view the files.

**Comment by PawelLipski** [comment]
And with `ci/docker-build-and-push.sh`... I see that that the lines about `DIRECTORY_HASH` are included in the snippets, but `docker-compose pull/build/push` are skipped, thus making some references to them unclear:

```markdown
Once we've got the directory hash, we check (`docker-compose pull`) whether the image with the given tag is already present
in the [virtuslab/git-machete-ci-tox repository on Docker Hub](https://hub.docker.com/r/virtuslab/git-machete-ci-tox/tags).

If there is no previous build for the given combination of Git version, Python version and contents of ci/tox directory,
`docker-compose pull` would return a non-zero exit code, although this can also mean a failure of the pull operation.
In either case, we need to construct the image from scratch.

Note that `docker-compose build` accepts additional arguments, namely `user_id ` and `group_id`; we'll explain their purpose in the next section.
```

**Comment by PawelLipski** [comment]
Also, for the purpose of filling up the snippet, I'd skip certain irrelevant details, like `--ansi never`, probably also simplify:

```shell
# If image is not found by pull, build the image and push it to the Docker Hub.
docker-compose --ansi never pull $image_name
# A very unpleasant workaround for https://github.com/docker/compose/issues/7258
# (since v1.25.1, `docker-compose pull` is NOT failing when it can't fetch the image).
image_tag=$(docker-compose --ansi never config | yq eval ".services.$image_name.image" -)
docker image inspect "$image_tag" &>/dev/null || {
```

to the previous form:

```shell
# If image is not found by pull, build the image and push it to the Docker Hub.
docker-compose pull $image_name || {
```

which is gonna be a little _confabulation_ but very useful for clarity
