### ISSUE TITLE
`git machete --help` returns an error

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#25]
```
$ git machete --help
No manual entry for git-machete
See 'man 7 undocumented' for help when manual pages are not available.
```

The help as for now is baked into machete itself and simply printed to stdout, it might be necessary to also make a git-compatible version of help - at least for the top-level help. The command-specific help might still be handled by machete itself.

**Comment by PawelLipski** [comment]
Might be not so easy to solve, considering that the arguably most prominent non-builtin git command nowadays, `git lfs`, has the exact same problem:
 
```
$ git lfs --help
No manual entry for git-lfs
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by PawelLipski** [comment]
...and the other very prominent non-standard command (maybe even more so than `lfs`), `git flow`, also fails in the same way on `--help` :/

**Comment by PawelLipski** [comment]
But still, a solution would be to ship (Homebrew/Ubuntu PPA at least) git-machete with a man page, doesn't need to be a complete one, it can as well be an overview of the tool with no details on specific subcommands.

**Comment by mkondratek** [comment]
This one causes inconsistency. :confused: 

A little bird told me that he gets angry because for `git machete` he must write just `help` (usually he gets this error first :rofl:) but for a specific command e.g. `git machete discover` the `--help` is required.

**Comment by PawelLipski** [comment]
As of v3.17.0, `git machete --help` finally displays a man page when installed via Homebrew (which is the primary installation channel). Closing this issue. For tracking the progress on other channels, let's use #895
