### ISSUE TITLE
Use a dedicated, low-privilege account on DockerHub for pushing the CI images

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#268]
As for now, my own personal account is used... which has privileges to e.g. add/remove users from the organization.

For the sake of security, a more limited service account should be used, similarly to how @git-machete-bot is used for the side-effecting actions performed against GitHub, like adding a release.

This account should ideally only have the privilege to do `docker push` to `gitmachete` organization, and nothing else.

On GitHub, I needed to open a regular account (there's fundamentally no difference b/w @git-machete-bot and my personal account, just in what repos each can access)...coz GitHub has no concept of _service account_ AFAIK. Let's check, maybe DockerHub has sth like that? or maybe it's possible to have a DockerHub token?

**Comment by rifel123** [comment]
As there won't be any change in this repository, but only in dockerhub and circleCI, let's document what was done here:
- technical user `gitmachetebot` has been to dockerhub organisation with only READ/WRITE permisions.
- circleCI now uses credentials of newly added `gitmachetebot` when pushing images to dockerhub in CI builds.
