### ISSUE TITLE
Restore dry-run for building of snaps

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#275]
To prevent failures like the one for 3.4.0: https://snapcraft.io/git-machete/builds/1552611 (`Specified icon 'logo.png' does not exist.` coz `snap/snapcraft.yml` still references `logo.png` while the file was moved to `graphics/logo.png`).

A dry-runs used to be executed on Travis for `develop` builds, pls look for .travis.yml in the git history. I had trouble migrating that to CircleCI... but probably manipulating with the `base` version in snapcraft.yml and CircleCI VM version should get it done 🕵🏻

**Comment by rifel123** [comment]
Closed with #280
