### ISSUE TITLE
Builds for `hotfix/*` branches should also trigger dry-runs of deployments

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#278]
Typically, a hotfix would address some issue with deployment (like https://github.com/VirtusLab/git-machete/pull/277)... actually, building snaps is NOT covered yet by a dry-run (see #275), but still, it'd be nice to dry-run deployments not only for `develop`, but also for hotfix builds

**Comment by rifel123** [comment]
closed with #275
