### ISSUE TITLE
What actually happens when git-machete is executed against Python 2 or 3.5?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#285]
There is a check for that versions in the code... but my suspicion is that Python will fail on syntax error (e.g. due to `f"..."`-style string interpolations) first. Let's verify and circumvent this issue if needed

**Comment by rifel123** [comment]
I have tested behaviour of git-machete against python 2.7 and 3.5.
Both version ended up with syntax error on type hints:
<img width="887" alt="Screenshot 2021-10-18 at 15 07 56" src="https://user-images.githubusercontent.com/73847352/137738058-62ca3d83-a97c-4650-94fc-dca37d781593.png">

Despite the fact that typing module was introduced in python 3.5, at that point typing variables was not allowed, so this version also fails at very same point.

Proposed solution: move `validate_python_version` from cli.py to git-machete (entry point script fro git-machete), to break flow  there if necessary.

**Comment by rifel123** [comment]
closed with #296
