### ISSUE TITLE
Resolve PEP-8 issues

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#30]
https://travis-ci.org/pasuder/git-machete/jobs/487311634

I really don't know what to do with 80 char line size limit though... maybe we should supress this particular check as for now.

**Comment by pasuder** [comment]
At this moment suppression of 80 char line size is enabled.

https://github.com/pasuder/git-machete/blob/450183cb6b66f7c112c3eab3d6cfed0ea05728fa/tox.ini#L28

IMO it would be good to try to decompose parts into function (it will eliminate indentation and stick to 80 chars in lines) and do some other things with code. I will do task for it later.

**Comment by PawelLipski** [comment]
TBH I'd stick to ignoring 80 char line length limit... I tried applying that limit in many places accross the codebase but IMO the result is much uglier/less readable compared to with more relaxed line length limit. I think e.g. Scala's default 160 feels much better.
