### ISSUE TITLE
Setup branch protection on master

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#31]

**Comment by pasuder** [comment]
Settings could be find under link: https://github.com/VirtusLab/git-machete/settings/branch_protection_rules/new

Proposing settings:

![zrzut ekranu z 2019-02-03 08-49-26](https://user-images.githubusercontent.com/3436085/52174182-c5ded600-2790-11e9-9c69-572cf1a7dcf2.png)

**Comment by PawelLipski** [comment]
Settings applied.
