### ISSUE TITLE
Unify the usage of `print(...)` vs `sys.std{out,err}.write`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#310]
Let's research if there's any advantage to using either of them (I'd especially take a look from testing/mockability perspective) and use one of them consistently everywhere. As for now, there's a lot of mess in this area.

**Comment by mohitsaxenaknoldus** [comment]
`print` is just a wrapper over `stdout` with some rich features. `print` first converts the object to a string (if it is not already a string). It will also put a space before the object if it is not the start of a line and a newline character at the end. While with `stdout`, you have to convert the object to a string yourself (by calling "str", for example) and there is no newline character. Moreover, `print` also supports passing a file. So IMO, `print` should be the way to go.

**Comment by PawelLipski** [comment]
Okay! `print` let it be then

**Comment by mohitsaxenaknoldus** [comment]
Please assign.

**Comment by mohitsaxenaknoldus** [comment]
Update: Surprisingly, a lot of things broke just by replacing `sys.std` with `print`. Working towards fixing it.

**Comment by PawelLipski** [comment]
Wow okay 😯 what were the problems, failing tests relying on some mocks for `sys.stdout`? 🤔

**Comment by PawelLipski** [comment]
Closed with #367
