### ISSUE TITLE
Enable Travis CI + add Travis badge to README

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#33]

**Comment by pasuder** [comment]
`.travis.yml` is provided in `setup_develop` branch: https://github.com/pasuder/git-machete/blob/setup_project/.travis.yml

The only thing to do is to enable it on Travis: https://travis-ci.org/account/repositories

![zrzut ekranu z 2019-02-03 09-00-53](https://user-images.githubusercontent.com/3436085/52174317-3cc89e80-2792-11e9-9bd6-ba02caa989c9.png)

**Comment by PawelLipski** [comment]
Badge link: `https://travis-ci.org/VirtusLab/git-machete.svg?branch=master`

**Comment by PawelLipski** [comment]
Closed via #13
