### ISSUE TITLE
discover: branch incorrectly inferred to be a root of dependency tree

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#5]
From #4 ([comment](https://github.com/VirtusLab/git-machete/issues/4#issuecomment-423775156)):

> 
> Right now I've got a case where the parent branch is not inferred despite the child being based on it (the huge_string_concat branch):
> 
> artur@y510p:~/projects/rchain$ git machete discover 
> Discovered tree of branch dependencies:
> 
>   dev
> 
>   huge_string_concat (diverged from origin)
> 
>   rho_parse
> I'd expect sth like this:
> 
> artur@y510p:~/projects/rchain$ git machete status
>   dev
>   │ 
>   └─huge_string_concat (diverged from origin)
>   │ 
>   └─rho_parse

**Comment by PawelLipski** [comment]
@ArturGajowy `v2.6.2-RC2` should fix this issue (remote counterparts of potential parents are now also taken into account during upstream inference), pls check

**Comment by ArturGajowy** [comment]
In the current state of my repo it no longer happens, feel free to close the issue - I'll report back should I spot anything.

**Comment by PawelLipski** [comment]
I can't determine whether the issue would happen under `v2.6.2-RC` and the old repository state :/ Closing as for now.
