### ISSUE TITLE
Wrong (?) fork point choice after resetting the root branch

### ISSUE THREAD

**Issue by ArturGajowy** [VirtusLab/git-machete#6]
Hello there! :wave: :smile:

I had the branch `pretty_spec` to be equal to `dev`, because I notoriously create branches after creating their commits off the previous branch I were at (:joy:). 

`pretty_spec` branch originally had only one commit, and was based on `normalizer_connectives_discard_bug`, which was based on `dev`. Most likely none of those facts were known to `machete` at that point.

I've since merged the `normalizer_connectives_discard_bug` to `upstream/dev`, doing a couple of force-push edits to it beforehand.

Today I reset `dev` to `upstream/dev`, which since had updates.

Now the forkpoint for `pretty_spec` is its tip.

## Expected behavior/subcommand output

I realize that's a twisted and chaotic workflow I tend to have, but I'd expect the fork-point to be `pretty_spec^`. For sure it shouldn't be the tip of the branch, b/c that results in 'no changes to rebase', which should only be the case when `parent_branch === current_branch`.

## Actual behavior/subcommand output

The full contents of my .git are available in https://github.com/ArturGajowy/rchain-git/tree/issue_6

```

artur@y510p:~/projects/rchain$ git machete --version
git-machete version 2.6.2
artur@y510p:~/projects/rchain$ git machete status -l
  dev
  │ 
  │ PrettyPritner: wrap match cases in `{}` to ensure parsable output
  │ PrettyPritner: wrap match case bodies in `{}` to ensure parsable output
  │ WIP Make GPrivate / unforgable names output parsable (yet still safe)
  │ PrettyPritner: wrap match target in `{}` to ensure parsable output
  │ PrettyPrinter: Remove spurious whitespace from `bundle` printout
  │ WIP PrettyPrinter: fix output of boolean operators for expressions
  │ WIP Normalized AST generation
  └─hold_my_beer (untracked)
  │ 
  │ Add scalafmt pre-commit hook
  │ WIP turn off scalafmt because git hook.
  └─local_changes
  │ │ 
  │ │ FIXME move the PrettyPrinter to models - MOVE TESTS TOO!!
  │ │ WIP Add HashM typeclass for stacksafe hashCode
  │ │ Add scalapb.compilerplugin as model's dependency
  │ │ WIP Add ProtoM
  │ │ Use stacksafe serializedSize in Chargable and Costs
  │ │ WIP Add StacksafeScalapbGenerator
  │ │ WIP FIXME Add custom stacksafe hashCode to proto-generated AST classes
  │ │ WIP StackSafety spec mods
  │ │ Diff
  │ │ WIP
  │ │ fixup! Diff
  │ │ WIP Serialization seems to work 1-1
  │ │ Extract StackSafetySpec companion for reuse across tests
  │ │ WIP
  │ └─staksafe_hashcode (ahead of origin)
  │   │ 
  │   │ WIP Recursion schemes for proto (de)serialization
  │   └─recursion_schemes
  │ 
  │ Add scalafmt pre-commit hook
  └─pre_commit_hook
  │ 
  └─pretty_spec (untracked)
  │ 
  │ Add MatchTest.parse for easier expression of more readable test cases
  │ Add rudimentary support for bound variables in MatchTest.parse
  └─rho_parse
artur@y510p:~/projects/rchain$ git machete log pretty_spec
artur@y510p:~/projects/rchain$ git machete fork-point pretty_spec 
d4af4a9a8ef28cafe5394f756395097c03a45120
```

## Additional diagnostics info

```
artur@y510p:~/projects/rchain$ git machete -v fork-point pretty_spec
git rev-parse --git-dir
git for-each-ref --format=%(refname:short) refs/heads
git rev-parse --abbrev-ref dev@{upstream}
git rev-parse --abbrev-ref hold_my_beer@{upstream}
git rev-parse --abbrev-ref local_changes@{upstream}
git rev-parse --abbrev-ref pre_commit_hook@{upstream}
git rev-parse --abbrev-ref recursion_schemes@{upstream}
git rev-parse --abbrev-ref rho_parse@{upstream}
git rev-parse --abbrev-ref staksafe_hashcode@{upstream}
git reflog --format=%H:%gs dev --
git reflog --format=%H:%gs hold_my_beer --
git reflog --format=%H:%gs local_changes --
git reflog --format=%H:%gs pre_commit_hook --
git reflog --format=%H:%gs recursion_schemes --
git reflog --format=%H:%gs rho_parse --
git reflog --format=%H:%gs staksafe_hashcode --
git reflog --format=%H:%gs upstream/dev --
git reflog --format=%H:%gs origin/local_changes --
git reflog --format=%H:%gs origin/pre_commit_hook --
git reflog --format=%H:%gs origin/recursion_schemes --
git reflog --format=%H:%gs origin/rho_parse --
git reflog --format=%H:%gs origin/staksafe_hashcode --
git log --max-count=10 --format=%H pretty_spec
d4af4a9a8ef28cafe5394f756395097c03a45120
```

Hope this helps! :)

**Comment by PawelLipski** [comment]
`git machete fork-point --debug pretty_spec` says the following:

```
(...a lot of logs...)
match_log_to_adjusted_reflogs(pretty_spec): commit d4af4a9a8ef28cafe5394f756395097c03a45120 found in adjusted reflog of dev
fork_point(pretty_spec): commit d4af4a9a8ef28cafe5394f756395097c03a45120 is the most recent point in history of pretty_spec to occur on adjusted reflog of any other branch or its remote counterpart (specifically: dev)

d4af4a9a8ef28cafe5394f756395097c03a45120
```

And indeed, when you take a look at `git reflog dev`:

```
plipski ~/rchain pretty_spec$ git reflog dev
d3fd1b90b (upstream/dev, dev) dev@{0}: reset: moving to upstream/dev
d4af4a9a8 (HEAD -> pretty_spec) dev@{1}: rebase -i (finish): refs/heads/dev onto 0051b5c9c1230bed1fc0319bf744ca086abe376d
80cbbd0ac dev@{2}: rebase -i (finish): refs/heads/dev onto 754703aee0fb8375dc981147b03566caf4a1ab24
(...older reflog entries...)
```
So basically there was an event in the history of `dev` (which wasn't just a reset event or branch creation event, thus we speak of "adjusted reflog") that ended up in `dev` being exactly `d4af4a9a8`. So I don't think the `fork-point`'s behavior was incorrect in this case :/  

What's more, git's native fork point algo says exactly the same:

```
plipski ~/rchain pretty_spec$ git merge-base --fork-point dev HEAD
d4af4a9a8ef28cafe5394f756395097c03a45120
```

**Comment by PawelLipski** [comment]
@ArturGajowy Just a simple remedy I can think of: 

```
git checkout pretty_spec
git machete update --fork-point HEAD^
```

Thus a new commit will be generated that's based off current `dev`, and doesn't appear on reflog of any other branch. After that, `git machete fork-point pretty_spec` should be `d3fd1b90bc95735704a07d183a3bd14130766722`, so parent commit of the rebased `pretty_spec`.

Pls let me know if this worked for you (unless the issue got fixed in some other way in the meantime).

**Comment by ArturGajowy** [comment]
I'm aware of the `--fork-point`, it always saves me when machete does a wrong fork point :) And it's great that once instructed to use a fork-point it seems to stick to it (probably b/c of the branch + reflog structure after rebase?).

The point of this issue was to not have to specify the fork-point in such cases.

> So basically there was an event in the history of dev (which wasn't just a reset event or branch creation event, thus we speak of "adjusted reflog") that ended up in dev being exactly d4af4a9a8

What kind of event would cause that? Of the things I might've done, it could be:
- delete branch + checkout from remote
- (can't think of more now)

So, nothing can be done and I should restrict my git idioms or use the `--fork-point` option? :)

**Comment by PawelLipski** [comment]
> And it's great that once instructed to use a fork-point it seems to stick to it (probably b/c of the branch + reflog structure after rebase?).

After rebase of branch X onto Y, the newly-created tip of X is automatically only present in the reflog of X and nowhere else (no other branch could even have "heard" of that new tip of X since it has just been created as a effect of the rebase).

> What kind of event would cause that? Of the things I might've done, it could be...

As the mentioned reflog of `dev` shows, there was the following event in the history of `dev`:

`d4af4a9a8 (HEAD -> pretty_spec) dev@{1}: rebase -i (finish): refs/heads/dev onto 0051b5c9c1230bed1fc0319bf744ca086abe376d`

So you rebased `dev` and after that rebase `dev` ended up being exactly `d4af4a9a8`... so I guess any reasonable fork point algorithm would state that `d4af4a9a8` is a part of `dev`'s specific history :/ Thus, it wouldn't recognize `pretty_spec`'s tip as specific to `pretty_spec` only.

> So, nothing can be done and I should restrict my git idioms or use the --fork-point option? :)

I'm afraid those are exactly the two viable options... it's all about balance between making machete's fork-point too restrictive or too lax wrt. what constitutes unique history of a given branch... as for now I think it's pretty balanced (at least definitely more than `git merge-base --fork-point`) but I'm happy to improve if possible :)

**Comment by ArturGajowy** [comment]
Thank you for the explanation!

The only other improvement (?) that comes to my mind is using the commit messages to find the fork point (that's how a human being would do that), possibly as a fallback / togglable strategy.

I think though it'd be a separate issue and the correct resolution for this particular issue would be "not a bug + won't fix :)"

**Comment by PawelLipski** [comment]
Done, created #11 for that :)

Also, an unrelated FYI: v2.8.0 has been released which automates slide-out to some extent - `traverse` now asks whether to slide out a branch if it's merged to its parent. By "merged" I understand commit-wise behind - commit-wise equality is not enough.
