### ISSUE TITLE
discover -C results in KeyError

### ISSUE THREAD

**Issue by blitz** [VirtusLab/git-machete#65]
# Overview

Using the `-C` option machete discover always dies with a key error. Discover without `-C` works. See below for details.

I can provide more debugging information on request, but `--debug` was a bit too verbose.

## Expected behavior/subcommand output

`-C` discovers only branches touched in the given timeframe.

## Actual behavior/subcommand output

```
% git machete discover -C "2 weeks ago"

Traceback (most recent call last):
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/bin/.git-machete-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packages/git_machete/cmd.py", line 2064, in main
    discover_tree()
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packages/git_machete/cmd.py", line 970, in discover_tree
    stale_branches = [b for b in non_root_fixed_branches if
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packages/git_machete/cmd.py", line 971, in <listcomp>
    last_checkout_timestamps[b] < threshold]
KeyError: 'cpulocal-tss-move'
```

## `git` and `git machete` versions

```
% git --version
git version 2.23.0
% git machete --version
git-machete version 2.12.1
```

## Additional diagnostics info

```
% git machete --verbose discover -C "2 weeks ago"
git rev-parse --git-dir
git for-each-ref --format=%\(refname:strip=2\)$'\t'%\(objectname\) refs/remotes
git for-each-ref --format=%\(refname:strip=2\)$'\t'%\(objectname\)$'\t'%\(upstream:strip=2\)$'\
t'%\(push:strip=2\) refs/heads
git rev-parse --since=2\ weeks\ ago
git reflog show --format=%gd:%gs --date=unix
Traceback (most recent call last):
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/bin/.git-machete-wrapped
", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packa
ges/git_machete/cmd.py", line 2064, in main
    discover_tree()
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packa
ges/git_machete/cmd.py", line 970, in discover_tree
    stale_branches = [b for b in non_root_fixed_branches if
  File "/nix/store/1lqinbfyri06mjgrnajvxz58zy9959la-git-machete-2.12.1/lib/python3.7/site-packa
ges/git_machete/cmd.py", line 971, in <listcomp>
    last_checkout_timestamps[b] < threshold]
KeyError: 'cpulocal-tss-move'
```

**Comment by blitz** [comment]
@PawelLipski If you have a minute to look into this, it would be much appreciated! :)

**Comment by PawelLipski** [comment]
Sorry for the delay! Will take a look soon

**Comment by PawelLipski** [comment]
@blitz Already done with the bugfix (and a couple others), let me just that test that for myself

**Comment by PawelLipski** [comment]
@blitz fix pushed as version 2.12.2, pls run pip install command (with or without sudo, as you did last time) with `--upgrade` flag

**Comment by PawelLipski** [comment]
Thank you for posting the issue! I would be grateful for spreading the word about the tool in your team/organization and/or for github stars ;)

**Comment by blitz** [comment]
@PawelLipski I can do one better. I've packaged it in https://github.com/NixOS/nixpkgs. :) Thanks for fixing the problem!

https://github.com/NixOS/nixpkgs/pull/73907

https://github.com/NixOS/nixpkgs/pull/74348

**Comment by PawelLipski** [comment]
Wow, thanks loads! 

Do you think there's a reasonable way to wire up the Nix package release to Travis pipeline without me nagging you constantly? ;)

**Comment by PawelLipski** [comment]
@blitz also if you suggest a paragraph in README on installation for NixOS users... esp. given that as for now the package is only available under `nixos-unstable` and `nixpkgs-unstable` channels https://nixos.org/nixos/packages.html?channel=nixos-unstable&query=git-machete
