### ISSUE TITLE
Tests can be excluded when installing the package

### ISSUE THREAD

**Issue by ilai-deutel** [VirtusLab/git-machete#71]
Currently, tests are installed along with the package:

```bash
> ls /usr/lib/python3.8/site-packages/git_machete
cmd.py  __init__.py  __pycache__  tests
```

Tests can typically be excluded from packages using [the `exclude` argument in setuptools `find_packages` function](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages). They can still be run during development, but the installed package will be lighter.

**Comment by PawelLipski** [comment]
Done, fixed as of [v2.12.10](https://github.com/VirtusLab/git-machete/releases/tag/v2.12.10)
