### ISSUE TITLE
Open a version-bump PR to NixOS/nixpkgs automatically on each release

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#79]
@blitz FYI

**Comment by blitz** [comment]
@PawelLipski  This already happens to some degree. When https://github.com/ryantm/nixpkgs-update discovers that any repo has a newer version of git-machete it will open a PR. The information about which distro has what version comes from: https://repology.org/project/git-machete/versions

In practice, this means that whenever someone bumps the Arch package, a merge request like [this](https://github.com/NixOS/nixpkgs/pull/79521#event-3019978514) pops up on nixpkgs.

**Comment by PawelLipski** [comment]
Oh ok, so basically it depends on (optionally) someone flagging the package on AUR and then (necessarily) @ilai-deutel updating it ;) Anyway, would be nice if that happens automatically regardless of AUR updates... hopefully automating that shouldn't be much work, will take a look soon
